### PR TITLE
Fix config directory for Flatpak

### PR DESCRIPTION
**Pull request by kevinsmia1939**
Hi,
I noticed that the config directory for Flatpak would be undefined. So I fix it to the  config location for Flatpak but kept other cases the same.

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
I will need to look further on where to put the config file for it to work properly first, don't merge yet.

**Comment by Julian-Hochhaus** [comment]
> I will need to look further on where to put the config file for it to work properly first, don't merge yet.

ok, thanks a lot for your effort, sorry if I have caused trouble. I am still too stupid to understand which files I need to update in what way to successful trigger the update on flathub. 
For pushing new releases to LG4X, I will more and more move the whole workflow to bumpver and github actions, so that everything for a new release is done by one command. If I got it half right, all the changes needed for flathub should be possible by automated commands as well?!

**Comment by kevinsmia1939** [comment]
Hi, I think the PR is ready now. No worries at all, the update on flathub failed because the old patch fail to patch because it is not needed anymore. 
The LG4X on the flathub github repository should trigger new build when the bot found new release on LG4XV2 github page.

**Comment by Julian-Hochhaus** [comment]
> Hi, I think the PR is ready now. No worries at all, the update on flathub failed because the old patch fail to patch because it is not needed anymore. The LG4X on the flathub github repository should trigger new build when the bot found new release on LG4XV2 github page.

Great, I assume if I want to release a new version I still need to add it here in the [metainfo.xml](https://github.com/Julian-Hochhaus/LG4X-V2/blob/master/data/io.github.julian_hochhaus.LG4X_V2.metainfo.xml)? 
And then the automatically triggered build should succeed?

**Review by Julian-Hochhaus — APPROVED** [review]

**Comment by kevinsmia1939** [comment]
Yes, that is correct. But I have already add a patch to add the correct version in metainfo file. So you don't need to re-release lg4x just to fix the version number in metainfo file.

**Pull request merged**
